import { invoke as tauriInvoke } from "@tauri-apps/api/core";

export type TauriCommand =
  | "analyze_project_initialization_markdown"
  | "append_transcript_events"
  | "approve_project_initialization_summary"
  | "attach_knowledge_to_transcript_session"
  | "collect_project_initialization_facts"
  | "create_knowledge_item"
  | "create_project"
  | "create_project_initialization"
  | "create_project_repository"
  | "create_task"
  | "create_task_agent_report"
  | "create_task_phase_artifact"
  | "create_transcript_session"
  | "create_acp_transcript_session"
  | "get_transcript_acp_identity"
  | "delete_project"
  | "delete_project_repository"
  | "drain_acp_events"
  | "drain_session_output"
  | "generate_project_initialization_summary"
  | "list_acp_registry_candidates"
  | "list_acp_sessions"
  | "list_acp_permissions"
  | "list_agent_doctor_reports"
  | "list_knowledge_items"
  | "load_acp_registry_session"
  | "list_model_catalog"
  | "list_project_initialization_facts"
  | "list_project_initialization_guardrails"
  | "list_project_initialization_knowledge_units"
  | "list_project_initialization_markdown_findings"
  | "list_project_initialization_summary"
  | "list_project_initializations"
  | "list_project_repositories"
  | "list_project_tasks"
  | "list_task_phase_artifacts"
  | "list_task_agent_reports"
  | "list_task_phase_run_receipts"
  | "link_task_phase_run_events"
  | "latest_task_phase_run_response_events"
  | "list_task_context_dispatch_receipts"
  | "list_projects"
  | "list_transcript_events"
  | "list_transcript_sessions"
  | "rename_transcript_session"
  | "resize_session"
  | "resolve_pending_task_context_dispatch"
  | "resolve_pending_task_phase_run"
  | "respond_acp_permission"
  | "save_project_initialization_guardrails"
  | "select_project_task_context"
  | "select_unified_project_task_context"
  | "send_acp_prompt"
  | "send_acp_prompt_with_context"
  | "send_task_phase_prompt"
  | "set_acp_model"
  | "start_acp_registry_session"
  | "start_codex_session"
  | "start_fake_session"
  | "stop_acp_session"
  | "stop_session"
  | "transition_task_phase"
  | "write_session_input";

export function invokeCommand<TResult>(
  command: TauriCommand,
  args?: Record<string, unknown>,
): Promise<TResult> {
  return args === undefined
    ? tauriInvoke<TResult>(command)
    : tauriInvoke<TResult>(command, args);
}
